development:
  adapter: postgresql
  encoding: utf8
  database: noladex/development
  username: postgres
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: utf8
  database: noladex/test
  username: postgres
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: utf8
  database: db/production
  pool: 5
  timeout: 5000
